models.py
from . import db
from flask_login import UserMixin


class FileContents(db.Model):
    __tablename__ = 'files'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(300))
    data = db.Column(db.LargeBinary)
    expiration_time = db.Column(db.Integer)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(15), unique=True)
    email = db.Column(db.String(50), unique=True)
    password = db.Column(db.String(80))
    files = db.relationship('FileContents', backref='users')

__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite3'
    db.init_app(app)

    app.config['SECRET_KEY'] = 'Thisissupposedtobesecret!'
    bootstrap = Bootstrap(app)
    login_manager = LoginManager()
    login_manager.init_app(app)

    from .models import User
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    login_manager.user_loader(load_user)
    login_manager.login_view = 'main.login'

    from .views import main 
    app.register_blueprint(main)

    return app

views.py
from flask import Blueprint, render_template, request, redirect, url_for, send_file, abort, jsonify
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash

from io import BytesIO

from datetime import datetime
from datetime import timedelta


from . import db
from .models import User, FileContents

from .utility import calc_remaining_lifetime, delete_expired_files
from .account_forms import LoginForm, RegisterForm
main = Blueprint('main', __name__)


from . import create_app

@main.route('/', methods=['POST', 'GET'])
def index():
    db.create_all(app=create_app())
    return render_template('index.html')



@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user, remember = form.remember.data)
                return redirect(url_for('main.dashboard'))

        return render_template('common/fail.html')

    return render_template('guest/login.html', form=form)


@main.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        new_user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()

        return render_template('common/success.html')

    return render_template('guest/signup.html', form=form)



@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))



@main.route('/upload-form', methods=['POST', 'GET'])
def upload_form():
    return render_template('user/upload-form.html')


@main.route('/upload', methods=['POST'])
def upload():
    file = request.files['inputFile']
    life_minutes = float(request.form['inputMinutes'])
    exp_time = datetime.now() + timedelta(minutes = life_minutes)

    if current_user.is_anonymous:
        author_id = -1
    else:
        author_id = current_user.id

    new_file = FileContents(name=file.filename, data=file.read(), expiration_time=exp_time, author_id=author_id)
    db.session.add(new_file)
    db.session.commit()

    #return render_template('success.html')
    if new_file:
        return jsonify({'id': new_file.id})
    return jsonify({'error': 'some error!'})



@main.route('/download/<int:id_file>')
def download(id_file):
    file_to_download = FileContents.query.filter_by(id = id_file).first()
    return send_file(BytesIO(file_to_download.data), attachment_filename = file_to_download.name, as_attachment = True)

@main.route('/show-all')
def show_all():

    delete_expired_files()

    if current_user.is_anonymous:
        author_id = -1
        template = 'guest/files-list.html'
    else:
        template = 'user/show-all.html'
        author_id = current_user.id

    all_files = FileContents.query.filter_by(author_id=author_id).all()
    #all_files = FileContents.query.all()

    return render_template(template, all_files=all_files)

@main.route('/show-single', methods=['POST', 'GET'])
def show_single():

    delete_expired_files()

    id_file = int(request.form['idFile'])
    searched_file = FileContents.query.filter_by(id=id_file).first()
    if searched_file:
       # from utility import calc_remaining_lifetime
        return render_template('common/show-single.html', file=searched_file,
                               remaining_lifetime=calc_remaining_lifetime(searched_file.expiration_time))
    else:
        abort(404) # not-found


@main.route('/dashboard')
@login_required
def dashboard():
    return render_template('user/dashboard.html', name=current_user.username)

templates/common/fail.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    fail
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/signin.css') }}">
{% endblock %}

{% block content %}
    <div class="container">

        <h2>fail :(</h2>
        <a href="{{ url_for('main.index') }}">home</a>

    </div> <!-- /container -->
{% endblock %}

templates/common/files-table.html
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <table class="table table-striped" border width="100%">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>expiration time</th>
            {#                <th>download</th>#}
        </tr>
        {% for file in all_files %}
            <tr>
                <td>{{ file.id }}</td>
                <td>{{ file.name }}</td>
                <td>{{ file.expiration_time }} </td>
                {#                    <td><a href={{ url_for('main.download', id_file = file.id) }}> click to download </a></td>#}
            </tr>
        {% endfor %}
    </table>
</div>

templates/common/inspect-file.html
<div class="container col-sm-9 col-sm-offset-3 col-md-5 col-md-offset-2 main">
    <form class="form-signin" method="POST" action="{{ url_for('main.show_single') }}">
        <h2 class="form-signin-heading">inspect single file by id</h2>
        <fieldset>
            <label for="idFile">id file:</label>
            <input type="text" id="idFile" name="idFile" class="form-control" required autofocus>
        </fieldset>
        <fieldset>
            <button class="btn btn-lg btn-primary btn-block" type="submit">submit</button>
        </fieldset>
    </form>

</div> <!-- /container -->

templates/common/show-single.html
{% extends "bootstrap/base.html" %}

{% block title %}
    show all
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/starter-template.css') }}">
{% endblock %}

{% block content %}

{% include 'guest/sidebar.html' %}

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <table class="table table-striped" border width="100%">
            <tr>
                <th>id</th>
                <th>name</th>
                <th>expiration time</th>
                <th>remaining</th>
                <th>download</th>
            </tr>

            <tr>
                <td>{{ file.id }}</td>
                <td>{{ file.name }}</td>
                <td>{{ file.expiration_time }} </td>
                <td>{{ remaining_lifetime }}</td>
                <td><a href={{ url_for('main.download', id_file = file.id) }}> click to download </a></td>
            </tr>

        </table>

    </div>
{% endblock %}

templates/common/success.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    success
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/signin.css') }}">
{% endblock %}

{% block content %}
    <div class="container">

        <h2>success!</h2>
        <a href="{{ url_for('main.index') }}">home</a>

    </div> <!-- /container -->
{% endblock %}

templates/guest/files-list.html
{% extends "bootstrap/base.html" %}

{% block title %}
    show all
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
{% endblock %}

{% block content %}
    <h2 class="col-lg-5 col-lg-offset-4">anonymous files</h2>

    {% include 'common/files-table.html' %}

    {% include 'common/inspect-file.html' %}

{% endblock %}

templates/guest/login.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
login
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/signin.css')}}">
{% endblock %}

{% block content %}
    <div class="container">

      <form class="form-signin" method="POST" action="{{ url_for('main.login') }}">
        <h2 class="form-signin-heading">please sign in</h2>
        {{ form.hidden_tag() }}
        {{ wtf.form_field(form.username) }}
        {{ wtf.form_field(form.password) }}
        {{ wtf.form_field(form.remember) }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">sign in</button>
      </form>

    </div> <!-- /container -->
{% endblock %}

templates/guest/sidebar.html
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">file eXchanger</span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">file eXchanger</a>
            </div>

            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('main.index') }}">home</a></li>
                    <li><a href="{{ url_for('main.dashboard') }}">dashboard</a></li>
                    <li><a href="{{ url_for('main.login') }}">login</a></li>
                    <li><a href="{{ url_for('main.signup') }}">sign up</a></li>
                </ul>
            </div><!-- nav-collapse -->
        </div>
    </nav>

templates/guest/signup.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
sign up
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/signin.css')}}">
{% endblock %}

{% block content %}
<div class="container">

  <form class="form-signin" method="POST" action="{{ url_for('main.signup') }}">
    <h2 class="form-signin-heading">sign up</h2>
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.username) }}
    {{ wtf.form_field(form.email) }}
    {{ wtf.form_field(form.password) }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">sign up</button>
  </form>

</div> <!-- /container -->
{% endblock %}

templates/index.html
{% extends "bootstrap/base.html" %}

{% block title %}
    file eXchanger
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/starter-template.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/signin.css') }}">
{% endblock %}

{% block content %}

    {% include 'guest/sidebar.html' %}


    <div class="container">

        <div class="starter-template">
            <h1>file eXchanger</h1>
            <p class="lead">Sign up. Then sign in. Then upload file. Then download it. Profit.</p>
        </div>

    </div><!-- container -->

    <hr style="width: 100%; color: black; height: 1px; background-color:black;"/>

    <div class="container">

        {#    action="{{ url_for('main.upload') }}"#}
        <form id="file-upload-ajax-form" class="form-signin" method="POST"
              enctype="multipart/form-data">
            <h2 class="form-signin-heading">upload file</h2>
            <fieldset>
                <label for="inputFile">file:</label>
                <input type="file" id="inputFile" name="inputFile" class="form-control" required autofocus>
            </fieldset>
            <fieldset>
                <label for="inputMinutes">lifetime in minutes:</label>
                <input type="text" id="inputMinutes" name="inputMinutes" class="form-control" required autofocus>
            </fieldset>
            <fieldset>
                <button id="upload-ajax" class="btn btn-lg btn-primary btn-block" type="submit">submit</button>
            </fieldset>
        </form>
        <div id="successAlert" class="alert alert-success" role="alert" style="display:none;"></div>
        <div id="errorAlert" class="alert alert-danger" role="alert" style="display:none;"></div>
    </div> <!-- /container -->



    <hr style="width: 100%; color: black; height: 1px; background-color:black;"/>

    <div class="container col-lg-offset-5 col-lg-5">
        <button class="btn"><a href="{{ url_for('main.show_all') }}">show all files you have access to</a></button>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/ajax-file-uploader.js') }}"></script>
{% endblock %}







{#    <div class="container">#}
{#        <form class="form-signin" method="POST" action="{{ url_for('main.show_single') }}">#}
{#            <h2 class="form-signin-heading">inspect single file by id</h2>#}
{#            <fieldset>#}
{#                <label for="idFile">id file:</label>#}
{#                <input type="text" id="idFile" name="idFile" class="form-control" required autofocus>#}
{#            </fieldset>#}
{#            <fieldset>#}
{#                <button class="btn btn-lg btn-primary btn-block" type="submit">submit</button>#}
{#            </fieldset>#}
{#        </form>#}
{##}
{#    </div> <!-- /container -->#}

templates/user/dashboard.html
{% extends "bootstrap/base.html" %}

{% block title %}
    cabinet
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
{% endblock %}

{% block content %}
    {% include 'user/navbar.html' %}


    {% include 'user/sidebar.html' %}


    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h2>Hello, {{ name }}</h2>
    </div>

{% endblock %}

templates/user/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">file eXchanger</span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">file eXchanger</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('main.logout') }}">log out</a></li>
            </ul>
        </div>
    </div>
</nav>

templates/user/show-all.html
{% extends "bootstrap/base.html" %}

{% block title %}
    show all
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
{% endblock %}

{% block content %}
     {% include 'user/navbar.html' %}

       {% include 'user/sidebar.html' %}

    {% include 'common/files-table.html' %}

    {% include 'common/inspect-file.html' %}

{% endblock %}

templates/user/sidebar.html
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="{{ url_for('main.upload_form') }}">upload file</a></li>
                <li><a href="{{ url_for('main.show_all') }}">show all</a></li>
            </ul>
        </div>
    </div>
</div>

templates/user/upload-form.html
{% extends "bootstrap/base.html" %}

{% block title %}
    upload file
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/signin.css') }}">
{% endblock %}

{% block content %}



    <div class="container">


        {#action="{{ url_for('main.upload') }}"#}
        <form id="file-upload-ajax-form" class="form-signin" method="POST" enctype="multipart/form-data">

            <p id="myElem" style="display:none">Saved</p>
            <h2 class="form-signin-heading">upload file</h2>
            <fieldset>
                <label for="inputFile">file:</label>
                <input type="file" id="inputFile" name="inputFile" class="form-control" required autofocus>
            </fieldset>
            <fieldset>
                <label for="inputMinutes">lifetime in minutes:</label>
                <input type="text" id="inputMinutes" name="inputMinutes" class="form-control" required autofocus>
            </fieldset>
            <fieldset>
                <button id="upload-ajax" class="btn btn-lg btn-primary btn-block" type="submit">submit</button>
            </fieldset>

            <a href="{{ url_for('main.index') }}">home</a>
        </form>
        <div id="successAlert" class="alert alert-success" role="alert" style="display:none;"></div>
        <div id="errorAlert" class="alert alert-danger" role="alert" style="display:none;"></div>

    </div> <!-- /container -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/ajax-file-uploader.js') }}"></script>
{% endblock %}









{#{% extends 'base.html' %}#}
{##}
{#{% block title %}upload file{% endblock %}#}
{##}
{#{% block css %}#}
{#<!-- Custom styles for this template -->#}
{#<link href="{{ url_for('static', filename='css/sign.css') }}" rel="stylesheet">#}
{#{% endblock %}#}
{##}
{#{% block body %}#}
{##}
{##}
{#<div class="container">#}
{##}
{#    <form class="form-signin" method="POST" action="{{ url_for('main.upload') }}" enctype="multipart/form-data">#}
{#        <h2 class="form-signin-heading">upload file</h2>#}
{#            <label for="inputFile" class="sr-only">file</label>#}
{#            <input type="file" id="inputFile" name="inputFile" class="form-control" required autofocus>#}
{#        <button class="btn btn-lg btn-primary btn-block" type="submit">submit</button>#}
{#    </form>#}
{##}
{#</div> <!-- /container -->#}
{#{% endblock %}#}


{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport"#}
{#          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">#}
{#    <meta http-equiv="X-UA-Compatible" content="ie=edge">#}
{#    <title>Document</title>#}
{#</head>#}
{#<body>#}
{##}
{#<form method="POST" action="{{ url_for('main.upload') }}" enctype="multipart/form-data">#}
{#    <input type="file" name="inputFile">#}
{#    <button type="submit">Submit</button>#}
{#</form>#}
{#</body>#}
{#</html>#}